---
- hosts: CSR-1000v-CML
  gather_facts: no

  tasks:
  - name: run show version on the routers
    ios_command:
     commands: show version | incl Version
     register: output
  - name: print output
    debug:
     var: output.stdout_lines
